/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** RunListPage — dashboard of active/recent runs */
        get: operations["listRuns"];
        put?: never;
        /**
         * PatientEntryPage — start a run from an IPS bundle
         * @description Single entry point for both PatientEntryPage tabs. The IPS bundle is supplied by the client — either from a file upload, or fetched by the browser via a client-side SMART launch (the UI completes the SMART token exchange and the `Patient/$summary` read itself; the BFF never touches the SMART token or the FHIR server for patient data).
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /**
         * RunDetailPage — stepper + review gate (polled)
         * @description The crux object. The UI renders the entire RunDetail screen from this response with no second call and no FHIR parsing. Poll until `status` is terminal OR an `awaiting_*` gate (then stop auto-advancing and show the review panel).
         */
        get: operations["getRunDetail"];
        put?: never;
        post?: never;
        /** Cancel a run (RunDetailPage / RunListPage) */
        delete: operations["cancelRun"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/review/careplan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CarePlanReview — approve / request_changes at the care-plan gate
         * @description The single care-plan approval mechanism (the only human gate; brief review is automated). approve → the workflow writes the plan as `active`; request_changes → the workflow regenerates the bundle with the feedback. Resumes a workflow paused at `awaiting_careplan_review`.
         */
        post: operations["submitReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/careplans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CarePlanList — persisted care plans */
        get: operations["listCarePlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/careplans/{careplanId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                careplanId: string;
            };
            cookie?: never;
        };
        /**
         * CarePlanDetail — read-only view of a persisted (already-approved) plan
         * @description Persisted plans are written as `active` only after in-run approval at the care-plan gate, so this is a read-only view (view-model + raw FHIR for the JSON viewer). Approval/rejection happens in-run via POST /runs/{runId}/review/careplan, not here.
         */
        get: operations["getCarePlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SystemStatus page — aggregate health */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Drives UI polling. UI keeps polling on `running`; STOPS and shows the care-plan review panel on `awaiting_careplan_review`; STOPS on terminal (`completed`/`failed`/`cancelled`). `awaiting_careplan_review` is an in-run human gate (design decision): the workflow pauses before writing and the plan is only persisted on approval. Requires a `ReviewCarePlan` SonataFlow Callback state (backend work-item), modeled on the ingester's ReviewManifest/ReviewArtifacts gates.
         * @enum {string}
         */
        RunStatus: "running" | "awaiting_careplan_review" | "completed" | "failed" | "cancelled";
        /** @enum {string} */
        StepStatus: "pending" | "active" | "done" | "error" | "skipped";
        /**
         * @description Only care-plan review is a human gate (brief review is automated, not a human step).
         * @enum {string}
         */
        ReviewGate: "careplan";
        /** @enum {string} */
        ReviewDecision: "approve" | "request_changes";
        /**
         * @description Stable, ordered pipeline step identifiers. UI maps key → label/icon; do NOT hardcode the list in the UI beyond this shared vocabulary. Keys are snake_case here and map to the PascalCase SonataFlow state names — the BFF owns the state-name → StepKey mapping when deriving `currentSteps` from a live instance. The automated steps map 1:1 to states in acp-writer/deploy/orchestrator/acp-writer-workflow.yaml; the workflow's inject/switch plumbing (InitFHIRReview, IncrementFHIRReview, CheckFHIRVerdict) is not surfaced as UI steps.
         * @enum {string}
         */
        StepKey: "scan_patient" | "resolve_guidelines" | "execute_dmn" | "retrieve_recommendations" | "compose_plan" | "generate_bundle" | "review_fhir" | "review_careplan" | "write_fhir" | "done";
        RunCreated: {
            runId: string;
            status: components["schemas"]["RunStatus"];
        };
        /** @description RunListPage rows. */
        RunSummary: {
            runId: string;
            status: components["schemas"]["RunStatus"];
            /** @description Display name resolved by the BFF (never make the UI parse a reference). */
            patientName?: string;
            patientReference?: string;
            /** @description Steps currently active. Usually one, but the pipeline is not strictly linear (steps can run in parallel), so this is a list. */
            currentSteps?: components["schemas"]["StepKey"][];
            /** @description Present once the run has produced a persisted plan. */
            careplanId?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PipelineStep: {
            key: components["schemas"]["StepKey"];
            status: components["schemas"]["StepStatus"];
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            /** @description Optional human-readable note (e.g. error summary). */
            detail?: string;
        };
        /** @description The full RunDetailPage state. */
        RunDetail: {
            runId: string;
            status: components["schemas"]["RunStatus"];
            patient?: components["schemas"]["PatientSummary"];
            steps: components["schemas"]["PipelineStep"][];
            /** @description Steps currently active. Usually one, but the pipeline is not strictly linear (steps can run in parallel), so this is a list. */
            currentSteps?: components["schemas"]["StepKey"][];
            /** @description Set to `careplan` when the care-plan gate is blocking, else null. Mirrors status but convenient for rendering. */
            awaitingReview?: components["schemas"]["ReviewGate"] | null;
            /** @description Present at the `careplan` gate — the same view-model as CarePlanDetail. */
            carePlan?: components["schemas"]["CarePlanView"] | null;
            /** @description Which care-plan review round this is (0 on the first review). Increments each time changes are requested and the plan is regenerated. */
            reviewIteration?: number;
            /** @description The review submitted in the previous round (when request_changes was chosen), so the UI can show what was asked for. Null on the first review. */
            previousFeedback?: components["schemas"]["ReviewAction"] | null;
            careplanId?: string;
            error?: components["schemas"]["RunError"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RunError: {
            stepKey?: components["schemas"]["StepKey"];
            message?: string;
        };
        /** @description Extracted by the BFF (or client for upload) from the IPS bundle. */
        PatientSummary: {
            name?: string;
            birthDate?: string;
            gender?: string;
            patientReference?: string;
            conditions?: components["schemas"]["CodedItem"][];
            medications?: components["schemas"]["CodedItem"][];
            allergies?: components["schemas"]["CodedItem"][];
            observations?: components["schemas"]["CodedItem"][];
        };
        CodedItem: {
            display: string;
            code?: string;
            system?: string;
        };
        PlanGoal: {
            /** @description Stable within the run; referenced by ReviewAction feedback. */
            id: string;
            description: string;
            rationale?: string;
            sourceCpgId?: string;
        };
        PlanActivity: {
            id: string;
            description: string;
            /** @description Links to the goal it serves. */
            goalId?: string;
            detail?: string;
        };
        /** @description A plan-level conflict flagged by the conflict_analyst node. Persisted plans reconstruct these from the conflict Provenance resources' extensions (never from note text); the live review view carries them on the brief. */
        PlanConflict: {
            /** @description Semantic (index-free) id, stable across request-changes regeneration. */
            id: string;
            /**
             * @description Display severity; drives the UI alert variant (info=blue, warning/critical=amber/red).
             * @enum {string}
             */
            severity?: "info" | "warning" | "critical";
            /**
             * @description The kind of conflict the analyst detected.
             * @enum {string}
             */
            category?: "overlap" | "contradiction" | "divergent_target" | "divergent_schedule" | "other";
            /**
             * @description Lifecycle — flips to acknowledged when a reviewer approves.
             * @enum {string}
             */
            status?: "detected" | "acknowledged" | "resolved";
            /** @description Analyst confidence ("low" | "medium" | "high"); recorded as the AIconfidence extension on the Provenance. */
            confidence?: string;
            /** @description Clinician-legible summary of the conflict. */
            description: string;
            /** @description The guideline recommendations that give rise to the conflict. */
            sources?: components["schemas"]["ConflictSource"][];
        };
        /** @description One guideline recommendation contributing to a conflict. */
        ConflictSource: {
            /** @description Source CPG identifier (e.g. SYN-HTN-2026-001). */
            cpgId: string;
            /** @description Source recommendation identifier within the CPG. */
            recommendationId?: string;
            /** @description Short quote from the source recommendation */
            excerpt?: string;
        };
        /** @description View-model reused by CarePlanReviewPanel and CarePlanDetail, rendered by GoalCard/ActivityCard/ConflictAlert. Raw FHIR is included ONLY for the "View FHIR JSON" viewer. NOTE: this is a deliberately flattened first cut. The internal model carries richer provenance (targets, dose/route/frequency, source refs, DMN audit); extending the view-model with those fields is tracked in #128. */
        CarePlanView: {
            goals?: components["schemas"]["PlanGoal"][];
            activities?: components["schemas"]["PlanActivity"][];
            /** @description Plan-level conflicts. For a persisted plan these are read back from the bundle's conflict Provenance resources; at the review gate they come from the planning brief. */
            conflicts?: components["schemas"]["PlanConflict"][];
            /** @description Raw FHIR bundle for the JSON viewer only. UI does not parse this for display. */
            fhirBundle?: {
                [key: string]: unknown;
            };
        };
        /** @description CarePlanList rows. patientName and generatedAt are BFF-resolved so the UI never renders a raw reference or an unparsed date. */
        CarePlanSummary: {
            id: string;
            patientName?: string;
            patientReference?: string;
            /** @description FHIR CarePlan.status (draft */
            status: string;
            /** Format: date-time */
            generatedAt?: string;
            /** @description Links back to the producing run. */
            runId?: string;
        };
        CarePlanDetail: components["schemas"]["CarePlanSummary"] & {
            patient?: components["schemas"]["PatientSummary"];
            view?: components["schemas"]["CarePlanView"];
        };
        ReviewAction: {
            decision: components["schemas"]["ReviewDecision"];
            /** @description Legacy display-name shortcut; prefer `reviewer`. */
            clinician?: string;
            reviewer?: components["schemas"]["ReviewerRef"];
            /** @description Overall free-text note. */
            comment?: string;
            /** @description Per-item feedback (CarePlanReviewPanel/FeedbackInput). Required-ish when decision=request_changes. */
            feedback?: components["schemas"]["FeedbackItem"][];
        };
        /** @description Identity of the human verifier. A SMART-on-FHIR launch would populate this from the token's fhirUser claim; today it is an optional request override (falls back to the ACP_REVIEWER_* config defaults). */
        ReviewerRef: {
            /** @description Human-readable verifier name recorded on the AI-Provenance. */
            display: string;
            /** @description FHIR reference to the verifier, e.g. "Practitioner/demo-clinician". */
            reference?: string;
            /** @description Identifier system for the verifier (paired with identifierValue). */
            identifierSystem?: string;
            /** @description Identifier value for the verifier (paired with identifierSystem). */
            identifierValue?: string;
        };
        FeedbackItem: {
            /** @description References a PlanGoal/PlanActivity/PlanConflict.id in the CarePlanView. */
            itemId: string;
            comment: string;
        };
        SystemStatus: {
            version?: string;
            decisionEngine?: {
                available?: boolean;
                modelsDeployed?: number;
                /** @description Deployed DMN decision models (SystemStatus page). */
                decisions?: {
                    id: string;
                    name: string;
                    sourceCpg?: string | null;
                }[];
            };
            knowledgeBase?: {
                available?: boolean;
                guidelines?: number;
                recommendations?: number;
                /** @description Registered clinical practice guidelines (SystemStatus page). */
                cpgs?: {
                    cpgId: string;
                    title: string;
                    version?: string | null;
                    issuingBody?: string | null;
                }[];
            };
        };
        Error: {
            message: string;
            code?: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRuns: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run summaries, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description FHIR IPS Bundle (resourceType=Bundle). BFF stores it in the MinIO PHI bucket. */
                    ipsBundle: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Run accepted; workflow started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getRunDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    submitReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewAction"];
            };
        };
        responses: {
            /** @description Review accepted; workflow resumes. Returns the updated run. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Run is not currently awaiting this gate */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCarePlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Care plan summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarePlanSummary"][];
                };
            };
        };
    };
    getCarePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                careplanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Care plan detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarePlanDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
