apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hapi-fhir
  labels:
    app.kubernetes.io/name: hapi-fhir
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: fhir-server
    app.kubernetes.io/part-of: cpg-to-acp
spec:
  replicas: {{ .Values.hapiFhir.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: hapi-fhir
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hapi-fhir
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: fhir-server
        app.kubernetes.io/part-of: cpg-to-acp
    spec:
      containers:
        - name: hapi-fhir
          image: {{ .Values.hapiFhir.image }}
          ports:
            - containerPort: {{ .Values.hapiFhir.service.port }}
              protocol: TCP
          env:
            - name: hapi.fhir.fhir_version
              value: R4
          readinessProbe:
            httpGet:
              path: /fhir/metadata
              port: {{ .Values.hapiFhir.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /fhir/metadata
              port: {{ .Values.hapiFhir.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            {{- toYaml .Values.hapiFhir.resources | nindent 12 }}
