apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hapi-fhir
  labels:
    app.kubernetes.io/name: hapi-fhir
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: cpg-to-acp
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.hapiFhir.service.port }}
      targetPort: {{ .Values.hapiFhir.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hapi-fhir
    app.kubernetes.io/instance: {{ .Release.Name }}
