{{- if .Values.loader.enabled }}
{{- $clusterDomain := .Values.clusterDomain | default "apps.example.com" -}}
{{- $acpWriterUiRoute := printf "https://acp-ui-%s.%s" .Release.Namespace $clusterDomain -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-loader
  labels:
    app.kubernetes.io/name: medplum-loader
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: data-loader
    app.kubernetes.io/part-of: cpg-to-acp
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: medplum-loader
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-loader
      restartPolicy: Never
      containers:
        - name: loader
          image: {{ .Values.image.registry }}/{{ .Values.image.namespace }}/{{ .Values.loader.image.name }}:{{ .Values.loader.image.tag }}
          imagePullPolicy: Always
          env:
            - name: MEDPLUM_BASE_URL
              value: http://{{ .Release.Name }}-medplum-server:{{ .Values.medplumServer.service.port }}
            - name: DATA_DIR
              value: /data
            - name: ACP_WRITER_LAUNCH_URI
              value: {{ $acpWriterUiRoute }}/launch
            - name: ACP_WRITER_REDIRECT_URI
              value: {{ $acpWriterUiRoute }}/
            - name: MEDPLUM_SUPERADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medplum-user-credentials
                  key: MEDPLUM_SUPERADMIN_PASSWORD
            - name: MEDPLUM_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: medplum-user-credentials
                  key: MEDPLUM_ADMIN_EMAIL
            - name: MEDPLUM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medplum-user-credentials
                  key: MEDPLUM_ADMIN_PASSWORD
            - name: MEDPLUM_PRACTITIONER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medplum-user-credentials
                  key: MEDPLUM_PRACTITIONER_PASSWORD
{{- end }}
