FROM node:22-alpine AS build
WORKDIR /app

COPY ../../shared/ui/ shared-ui/
RUN cd shared-ui && npm ci && npm run build

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginxinc/nginx-unprivileged:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/templates/default.conf.template
EXPOSE 8080
