server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass ${API_URL}/api/;
    }

    location /health {
        proxy_pass ${API_URL}/health;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
