image:
  registry: image-registry.openshift-image-registry.svc:5000
  namespace: sschifma-cpg-to-acp
  name: decision-service
  tag: phase2

replicas: 1

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

service:
  port: 8081
