{{- range $name, $pod := .Values.pods }}
{{- if $pod.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  labels:
    app.kubernetes.io/name: cpg-ingester-{{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: cpg-to-acp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cpg-ingester-{{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}
